import { GoogleSpreadsheet } from "google-spreadsheet";
import { JWT } from "google-auth-library";

async function initGooleAuth() {
  // Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
  const serviceAccountAuth = new JWT({
    // env var values here are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
    key: process.env.GOOGLE_PRIVATE_KEY?.replace(/\\n/g, "\n"),
    scopes: ["https://www.googleapis.com/auth/spreadsheets"],
  });

  return serviceAccountAuth;
}

export async function startGoogleSheet(url = "<the sheet ID from the url>") {
  const serviceAccountAuth = await initGooleAuth();
  const doc = new GoogleSpreadsheet(url, serviceAccountAuth);
  return doc;
}
