# 해당 Job의 이름을 아래와 같이 설정하여 Actions 탭에서 확인할 수 있게 설정합니다.
name: notion-scheduler

on:
  schedule:
    # Executes at 1:00 AM UTC every Monday, which is 10:00 am Korean time every Monday
    # 한국 표준시(KST)는 세계 협정시(UTC)보다 9시간 빠릅니다.
    # 따라서 GitHub Actions 워크플로가 한국 시간으로 오후 10:00에 실행되도록 예약하려면 cron 식이 오전 1:00 UTC에 실행되도록 설정해야 합니다.
    - cron: "0 1 * * 1"

jobs:
  execute_code:
    runs-on: ubuntu-latest

    steps:
      # 해당 레포지토리로 check-out하는 Action을 불러왔습니다.
      - name: Checkout code
        uses: actions/checkout@v3

      # Node 환경을 설정하여 npm 커맨드를 사용할 수 있도록 하는 Action을 불러옵니다.
      # 여기에서는 18 버전을 사용하고 있습니다.
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # github security를 통해 생성한 secret들로 환경변수 파일을 생성합니다.
      - name: access to secrets
        run: |
          echo "YOUTUBE_URL=$YOUTUBE_URL" >> .env
          echo "GOOGLE_SHEET_ID=$GOOGLE_SHEET_ID" >> .env
          echo "GOOGLE_SERVICE_ACCOUNT_EMAIL=$GOOGLE_SERVICE_ACCOUNT_EMAIL" >> .env
          echo "GOOGLE_PRIVATE_KEY=$GOOGLE_PRIVATE_KEY" >> .env
        env:
          YOUTUBE_URL: ${{secrets.YOUTUBE_URL}}
          GOOGLE_SHEET_ID: ${{secrets.GOOGLE_SHEET_ID}}
          GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL}}
          GOOGLE_PRIVATE_KEY: ${{secrets.GOOGLE_PRIVATE_KEY}}

      # pnpm과 몇가지 npm 패키지를 설치합니다.
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
            - args: [--global, gulp, prettier, typescript]

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      # 해당 프로젝트에서 사용하는 모든 라이브러리와 Surge를 설치합니다.
      - name: Install dependencies
        run: pnpm install

      # 해당 타입스크립트 프로젝트를 빌드합니다.
      - name: Build TypeScript
        run: pnpm build

      # 코드를 실행합니다.
      - name: Execute code
        run: pnpm start
